bf16: true
cutoff_len: 802816
dataset: null
ddp_timeout: 180000000
deepspeed: src/sft/configs/deepspeed/ds_z3_config.json
do_train: true
enable_liger_kernel: true
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 1
learning_rate: 0.0001
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 64
lora_target: all
lr_scheduler_type: cosine
max_samples: 2000000
model_name_or_path: -VL-2B-Instruct
num_train_epochs: 20.0
output_dir: checkpoint/2B_Binary-Guard/binary_classification/binary_classification_qwen2-vl-2b_bs64*1_20epoch_lora_2B
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 64
plot_loss: true
preprocessing_num_workers: 16
save_steps: 200
save_total_limit: 20
stage: sft
template: qwen2_vl
warmup_ratio: 0.1
