### model
model_name_or_path: models/qwen2-vl-2b

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 16
lora_dropout: 0.05
deepspeed: ../configs/deepspeed/ds_z2_config.json 

### dataset
dataset: 
template: qwen2_vl
cutoff_len: 3072
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 300

### output
output_dir: ../../../checkpoint/2B_Binary-Guard/
logging_steps: 1
save_steps: 500
save_total_limit : 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
enable_liger_kernel: true

